### ISSUE TITLE
Alice v2.1.1 requires first constructor parameter to be PersisterInterface

### ISSUE THREAD

**Issue by Verber** [KnpLabs/rad-fixtures-load#14]
As a result 

php app/console rad:fixtures:load 

returns this

Catchable Fatal Error: Argument 1 passed to Nelmio\Alice\Fixtures::__construct() must be an instance of Nelmio\Alice\PersisterInterface, instance of Doctrine\ORM\EntityManager given

**Comment by Verber** [comment]
Added pull request with fix https://github.com/KnpLabs/rad-fixtures-load/pull/16

**Comment by einenlum** [comment]
PR merged.
