### ISSUE TITLE
Add it to nelmio/alice readme

### ISSUE THREAD

**Issue by akovalyov** [KnpLabs/rad-fixtures-load#5]

**Comment by PedroTroller** [comment]
Wut ?

**Comment by akovalyov** [comment]
@PedroTroller do you want other people to use this bundle? :) In this case, someone should add it to https://github.com/nelmio/alice#installation, no? IMO, it is the most flexible and zero-configuration fixtures loader for alice.

**Comment by akovalyov** [comment]
Sorry, that it was not so clear.

**Comment by PedroTroller** [comment]
:+1:

**Comment by PedroTroller** [comment]
@akovalyov Done ! https://github.com/nelmio/alice/pull/221
