### ISSUE TITLE
change the name

### ISSUE THREAD

**Issue by theofidry** [KnpLabs/rad-fixtures-load#9]
Why such a weird name and not sticking to bundle's name conventions like `AliceBundle` or `AliceFixturesBundle`?

Otherwise great library, happy to have an alternative to [Hautelook/AliceBundle](https://github.com/hautelook/AliceBundle) which is more well designed! :)

**Comment by PedroTroller** [comment]
@theofidry Thanks \o/

Why these kind of names ? Because for us, our rad components are opened for other integrations than Symfony2 one. So, it's a librairy with a Symfony integration... not just a Symfony bundle.

**Comment by theofidry** [comment]
Ok so you're putting another non symfony specific layer on top of [`nelmio/alice`](https://github.com/nelmio/alice) before applying the bundle logic.

In that case why not trying to completely extract it? That way you have a repository for you component which is generic, and then another repository for the bundle. If someone want then to port it to another framework he would then be able to use the component in which there is nothing symfony specific.

Another way to avoid this as the component is quite light at the merge the component back to [`nelmio/alice`](https://github.com/nelmio/alice).

**Comment by docteurklein** [comment]
I guess it simplifies a lot the maintainability of the lib, and reduces the install/contribute complexity.

**Comment by theofidry** [comment]
Yes but as of now the first thing you see in this library is the usage as a bundle in a Symfony context which is a little bit confusing. Maybe for now it's better to keep it this way as it's more convenient to maintain and develop.

Otherwise for the name it's just that I don't like it and find `AliceFixtures` (closer to similar libraries like [`AliceFixturesBundle`](https://github.com/h4cc/AliceFixturesBundle) and [`DoctrineFixturesBundle`](https://github.com/doctrine/DoctrineFixturesBundle). But it may just be my opinion :p

**Comment by docteurklein** [comment]
bah, what matters in the end is not the package , but the present inside right? :)

**Comment by PedroTroller** [comment]
For the moment we just have a Symfony Integration... So I've just described how to use it with Symfony... If you want to add an other integration, I'll write a documentation for it, I promise :smile:

**Comment by theofidry** [comment]
Crappy package with crappy name is trash, great package with weird name is good enough, great package with good name is best :D

**Comment by theofidry** [comment]
Anyway expect some contributions soon ;)

**Comment by docteurklein** [comment]
you forgot «crappy package with awesome name is still trash.»

**Comment by theofidry** [comment]
I guess I've still not woken up, it should be the first^^
